const vacanciesData = [
  {
    "id": "VAC-001",
    "role": "Gestor de Contratos (Confidencial)",
    "department": " Gerencia de Expansión Brownfield y Grandes Superficies",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-01-13",
    "status": "Cancelada",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-002",
    "role": "Jefe Comercial Media",
    "department": " Dirección Omnichannel & Digital Sales",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-003",
    "role": "Jefe Comercial Autoplaza",
    "department": "Gerencia Comercial Chile",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-004",
    "role": "Jefe Comercial Media",
    "department": "Dirección Omnichannel & Digital Sales",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-01-18",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-005",
    "role": "Coordinador de Campañas",
    "department": "Dirección Omnichannel & Digital Sales",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-006",
    "role": "Coordinadora Planificación Comercial ",
    "department": "Gerencia Divisional Chile",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-007",
    "role": "Jefe de Digitalización Comercial (confidencial)",
    "department": "Subgerencia Planificación Comercial",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-01-08",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-008",
    "role": "Director de Marca",
    "department": "Gerencia de Marketing y Experiencia",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-01-05",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-009",
    "role": "Director de Planeamiento y Control de Gestión de Marketing",
    "department": "Gerencia de Marketing y Experiencia",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2025-12-29",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-010",
    "role": "Administrador de Proyecto (confidencial)",
    "department": "Proyectos y Construcción",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-01-23",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-011",
    "role": "Administrador de Proyecto (confidencial)",
    "department": "Proyectos y Construcción",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-01-23",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-012",
    "role": "Ejecutivo Operacion Tiendas",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-013",
    "role": "Asistente de Mall",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-014",
    "role": "Subgerente Mall Tobalaba",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-015",
    "role": "Subgerente Mall ",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-016",
    "role": "Asistente de Mall",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-017",
    "role": "Ejecutivo Clientes",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2025-11-19",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-018",
    "role": "Ejecutivo Clientes",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-019",
    "role": "Jefe Sustentabilidad",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-020",
    "role": "Coordinador de Obras de Construcción",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-021",
    "role": "Ejecutivo Operacion Tiendas",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-022",
    "role": "Ejecutivo Operacion Tiendas",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-023",
    "role": "Paisajista",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-024",
    "role": "Ejecutivo Clientes",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-025",
    "role": "Jefe Zonal de Operacion",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-026",
    "role": "Controller Cumplimiento Ambiental",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-01-27",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-027",
    "role": "Ejecutivo Operacion Tiendas (confidencial)",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-02-03",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-028",
    "role": "Ejecutivo Operacion Tiendas (confidencial)",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-02-03",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-029",
    "role": "Tecnico en Prevención",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-02-03",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-030",
    "role": "Ejecutivo Operacion Tiendas",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-03-06",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-031",
    "role": "Ejecutivo Clientes",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-01-29",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-032",
    "role": "Ejecutivo Clientes",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-01-29",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-033",
    "role": "Ejecutivo Clientes",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-01-30",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-034",
    "role": "Jefe Operaciones Comerciales",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-02-03",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-035",
    "role": "Jefe Operaciones Comerciales",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-036",
    "role": "Analista Control De Gestion",
    "department": "Gerencia de Estregia y Performance ",
    "hrbp": "María Jesús Jiménez ",
    "location": "Chile",
    "postedDate": "2026-01-29",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-037",
    "role": "Asistente de Mall",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-01-28",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-038",
    "role": "Ejecutivo Revisor de Especialidades",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-02-10",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-039",
    "role": "Asistente de Mall",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-01-05",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-040",
    "role": "Ejecutivo Clientes",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-01-28",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-041",
    "role": "Ejecutivo Clientes",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-01-29",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-042",
    "role": "Ejecutivo Clientes",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-01-28",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-043",
    "role": "Ejecutivo Clientes",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-01-29",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-044",
    "role": "Prevencionista de Riesgos",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-01-27",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-045",
    "role": "Prevencionista de Riesgos",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-01-28",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-046",
    "role": "Data Engineer",
    "department": "Gerencia de Tecnología ",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2025-11-18",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-047",
    "role": "Jefe de Proyecto ",
    "department": "Gerencia de Tecnología ",
    "hrbp": "María Jesús Jiménez ",
    "location": "Chile",
    "postedDate": "2025-12-12",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-048",
    "role": "Arquitecto Sap * Hana ",
    "department": "Proyecto SAP",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2025-11-18",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-049",
    "role": "Jefe FICO",
    "department": "Gerencia de Tecnología ",
    "hrbp": "María Jesús Jiménez ",
    "location": "Chile",
    "postedDate": "2026-02-12",
    "status": "Cancelada",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-050",
    "role": "Senior Data Architect ",
    "department": "Gerencia de Tecnología ",
    "hrbp": "María Jesús Jiménez ",
    "location": "Chile",
    "postedDate": "2025-09-05",
    "status": "Cancelada",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-051",
    "role": "Lider de Ambientes Sap ",
    "department": "Proyecto SAP",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2025-11-24",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-052",
    "role": "Technical Lead Sap",
    "department": "Proyecto SAP",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-12-02",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-053",
    "role": "Analista de Cumplimiento ",
    "department": "Gerencia Legal ",
    "hrbp": "María Jesús Jiménez ",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Stand By",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-054",
    "role": "Analista Control de Gestión ",
    "department": "Gerencia Estrategia y Performance",
    "hrbp": "María Jesús Jiménez ",
    "location": "Chile",
    "postedDate": "2026-01-12",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-055",
    "role": "Gerente de Proyecto SAP",
    "department": "Proyecto SAP",
    "hrbp": "María Jesús Jiménez ",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Cancelada",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-056",
    "role": "Jefe de Inversiones ",
    "department": "Gerencia de Estrategia y Performance",
    "hrbp": "María Jesús Jiménez ",
    "location": "Chile",
    "postedDate": "2026-01-16",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-057",
    "role": "Subgerente de Riesgo ",
    "department": "Gerencia Legal ",
    "hrbp": "María Jesús Jiménez ",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-058",
    "role": "Tech Lead ",
    "department": "Gerencia de Tecnología ",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-01-19",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-059",
    "role": "Analista Control de Gestión ",
    "department": "Gerencia Estrategia y Performance",
    "hrbp": "María Jesús Jiménez ",
    "location": "Chile",
    "postedDate": "2026-02-10",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-060",
    "role": "Director de Construcción - Concepción",
    "department": "Proyectos y Construcción",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2025-12-09",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-061",
    "role": "Director de Construcción - Santiago",
    "department": "Proyectos y Construcción",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2025-12-09",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-062",
    "role": "Director de Construcción Chile",
    "department": "Proyectos y Construcción",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-01-30",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-063",
    "role": "Jefe Gestión Permisos y Gestión Vial",
    "department": "Gerencia de Expansión Brownfield y Grandes Superficies",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-01-05",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-064",
    "role": "Practicante Profesional",
    "department": "Gerencia Comercial Perú",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2025-12-03",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-065",
    "role": "Practicante Profesional",
    "department": "Gerencia Comercial Perú",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2025-12-19",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-066",
    "role": "Ejecutivo Operacion Tienda",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-03-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-067",
    "role": "Ejecutivo Operacion Tienda",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2025-11-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-068",
    "role": "Ejecutivo Comercial Jr.",
    "department": "Gerencia Comercial Perú",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2025-11-10",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-069",
    "role": "Practicante Profesional",
    "department": "Gerencia Regional de Tecnología",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2025-12-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-070",
    "role": "Ejecutivo de Clientes y Marketing",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2025-12-24",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-071",
    "role": "Analista de Gestión de Proyectos",
    "department": "Gerencia de Estrategia y Performance",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2025-12-11",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-072",
    "role": "Ejecutivo Comercial Senior (confidencial)",
    "department": "Gerencia Comercial Perú",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2025-12-18",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-073",
    "role": "Ejecutivo Comercial (confidencial)",
    "department": "Gerencia Comercial Perú",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2025-12-18",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-074",
    "role": "Director de Mall",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2025-12-29",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-075",
    "role": "Adminsitrador de Centro Comercial",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-01-13",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-076",
    "role": "Adminsitrador de Centro Comercial",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-01-13",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-077",
    "role": "Jefe de Prevención (confidencial)",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-01-16",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-078",
    "role": "Coordinador de Energía (confiendencial)",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-01-16",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-079",
    "role": "Ejecutivo Revisor de Especialidades",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-01-22",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-080",
    "role": "Ejecutivo Revisor de Especialidades",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-01-22",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-081",
    "role": "Analista de Cobranzas",
    "department": "Gerencia de Administración",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-01-29",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-082",
    "role": "Analista de Control de Gestion",
    "department": "Gerencia de Administración",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-02-06",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-083",
    "role": "Ejecutivo de Clientes y Marketing",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2025-12-30",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-084",
    "role": "Director de Proyectos",
    "department": "Proyectos y Construcción",
    "hrbp": "Maria Jose Carrizo",
    "location": "Perú",
    "postedDate": "2026-02-02",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-085",
    "role": "Ejecutiva Espacios Publicitarios",
    "department": "Gerencia Divisional Chile y Colombia ",
    "hrbp": "Laura Camargo",
    "location": "Colombia",
    "postedDate": "2026-01-05",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-086",
    "role": "Ejecutiva de Ventas MNZ",
    "department": "Subgerencia Mallplaza Manizales",
    "hrbp": "Laura Camargo",
    "location": "Colombia",
    "postedDate": "2026-01-05",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-087",
    "role": "Director de Construcción La Serena",
    "department": "Proyectos y Construcción ",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2025-12-09",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-088",
    "role": "Jefe de Marketing Chile",
    "department": "Marketing y Experience",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2025-12-16",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-089",
    "role": "Analista Control de Nómina y Procesos",
    "department": "Personas",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2025-12-18",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-090",
    "role": "Director de Proyectos - Piura",
    "department": "Proyectos y Construcción",
    "hrbp": "Maria Jose Carrizo",
    "location": "Perú",
    "postedDate": "2025-12-17",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-091",
    "role": "Lider de Arquitectura- Reemplazp Licencia Materna",
    "department": "Proyectos y Construcciones",
    "hrbp": "Laura Camargo",
    "location": "Colombia",
    "postedDate": "2026-01-06",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-092",
    "role": "Practicante Universitario",
    "department": "Subgerencia Legal Colombia",
    "hrbp": "Laura Camargo",
    "location": "Colombia",
    "postedDate": "2026-01-15",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-093",
    "role": "Ejecutiva de Clientes CAL",
    "department": "Subgerencia Mallplaza Cali",
    "hrbp": "Laura Camargo",
    "location": "Colombia",
    "postedDate": "2026-02-03",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-094",
    "role": "Aprendiz Sena CTG",
    "department": "Subgerencia Mallplaza Cartagena",
    "hrbp": "Laura Camargo",
    "location": "Colombia",
    "postedDate": "2026-01-02",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-095",
    "role": "Product Manager",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-02-16",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-096",
    "role": "Asistente de Mall",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-02-16",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-097",
    "role": "Asistente de Mall",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-02-16",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-098",
    "role": "Asistente de Mall",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-02-16",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-099",
    "role": "Asistente de Mall",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-02-17",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-100",
    "role": "Asistente de Gerencia",
    "department": "Gerencia de Administración",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-02-16",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-101",
    "role": "Director de Construcción Perú",
    "department": "Proyectos y Construcción",
    "hrbp": "Maria Jose Carrizo",
    "location": "Perú",
    "postedDate": "2026-03-24",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-102",
    "role": "Ejecutivo de Clientes y Marketing",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-02-26",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-103",
    "role": "Directora de Experiencia",
    "department": "Gerencia de Marketing y Experiencia",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2025-12-19",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-104",
    "role": "Directora de Marketing Chile",
    "department": "Gerencia de Marketing y Experiencia",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2025-11-20",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-105",
    "role": "Analista Control de Gestión ",
    "department": "Gerencia Estrategia y Performance",
    "hrbp": "María Jesús Jiménez ",
    "location": "Chile",
    "postedDate": "2026-03-05",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-106",
    "role": "Analista Aseguramiento de Ingreso",
    "department": "Gerencia de Administración ",
    "hrbp": "María Jesús Jiménez ",
    "location": "Chile",
    "postedDate": "2026-03-02",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-107",
    "role": "Subgerente de Brownfield",
    "department": "Gerencia de Expansión Brownfield y Grandes Superficies",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-03-16",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-108",
    "role": "Practicante",
    "department": "Gerencia de Expansión Brownfield y Grandes Superficies",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-02-23",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-109",
    "role": "PM",
    "department": "Desarrollo de Nuevos Negocios",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-02-23",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-110",
    "role": "Practicante",
    "department": "Gerencia de Marketing y Experiencia",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-02-23",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-111",
    "role": "Subgerente de Exploración",
    "department": "Desarrollo de Nuevos Negocios",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-02-23",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-112",
    "role": "4 administradores*",
    "department": "Sin Departamento",
    "hrbp": "Sin HRBP",
    "location": "Desconocido",
    "postedDate": "2026-03-24",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-113",
    "role": "Director de Lima",
    "department": "Sin Departamento",
    "hrbp": "Sin HRBP",
    "location": "Desconocido",
    "postedDate": "2026-03-24",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-114",
    "role": "3 adm peru",
    "department": "Sin Departamento",
    "hrbp": "Sin HRBP",
    "location": "Desconocido",
    "postedDate": "2026-03-24",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-115",
    "role": "Arquitecto",
    "department": "Proyectos y Construcción",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-02-23",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-116",
    "role": "Jefe de DO",
    "department": "Talento y Cultura",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-02-18",
    "status": "Closed",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-117",
    "role": "Aprendiz Sena PROYECTOS",
    "department": "Proyectos y Construcciones",
    "hrbp": "Laura Camargo",
    "location": "Colombia",
    "postedDate": "2026-02-23",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-118",
    "role": "Analista de Gestion Comercial",
    "department": "Gerencia Comercial",
    "hrbp": "Laura Camargo",
    "location": "Colombia",
    "postedDate": "2026-03-24",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-119",
    "role": "Analista de Finanzas ",
    "department": "Gerencia de Finanzas y Relación con Inversionistas",
    "hrbp": "María Jesús Jiménez ",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-120",
    "role": "Analista Financiero",
    "department": "Gerencia Estrategia y Performance",
    "hrbp": "María Jesús Jiménez ",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-121",
    "role": "Sin Cargo",
    "department": "Sin Departamento",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-122",
    "role": "Sin Cargo",
    "department": "Sin Departamento",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-123",
    "role": "Arquitecto",
    "department": "Proyectos y Construcción",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-02-23",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-124",
    "role": "Subgerente de Brownfield Chile",
    "department": "Brownfield y Grandes Superficies",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-03-16",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-125",
    "role": "Administrador de Obra ",
    "department": "Proyectos y Construcción",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-03-10",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-126",
    "role": "Administrador de Obra La serena",
    "department": "Proyectos y Construcción",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-03-10",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-127",
    "role": "Administrador de Obra Oeste",
    "department": "Proyectos y Construcción",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-03-10",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-128",
    "role": "Director (confidencial)",
    "department": "Proyectos y Construcción",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-03-06",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-129",
    "role": "Director (confidencial)",
    "department": "Proyectos y Construcción",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-03-06",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-130",
    "role": "PM Studios",
    "department": "Gerencia de Marketing y Experiencia",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-03-24",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-131",
    "role": "Administrativo de Pagos y Contratos (confidencial)",
    "department": "Gerencia de Marketing y Experiencia",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-03-13",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-132",
    "role": "Jefe de Experiencia Clientes",
    "department": "Gerencia de Marketing y Experiencia",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-03-16",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-133",
    "role": "Jefe de Marketing Pre y postnatal",
    "department": "Gerencia de Marketing y Experiencia",
    "hrbp": "Maria Jose Carrizo",
    "location": "Chile",
    "postedDate": "2026-03-05",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-134",
    "role": "Coordinador de Prevención Temporal",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-03-02",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-135",
    "role": "Practicante de Control de Gestión",
    "department": "Gerencia Estrategia y Performance",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-03-10",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-136",
    "role": "Jefe Comercial",
    "department": "Gerencia Comercial Perú",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-03-12",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-137",
    "role": "Practicante de Administración",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-03-20",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-138",
    "role": "Coordinador de Operaciones",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-03-20",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-139",
    "role": "Practicante de Administración",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-03-20",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-140",
    "role": "Coordinador de Operaciones",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-03-20",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-141",
    "role": "Coordinador de Operaciones",
    "department": "Gerencia de Operaciones",
    "hrbp": "Patricia Bustamante",
    "location": "Perú",
    "postedDate": "2026-03-20",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-142",
    "role": "Ingeniero de Procesos Operacionales",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-03-11",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  },
  {
    "id": "VAC-143",
    "role": "Jefe de Control Operacional",
    "department": "Gerencia de Operaciones",
    "hrbp": "Seba Soto",
    "location": "Chile",
    "postedDate": "2026-03-23",
    "status": "Open",
    "priority": "Medium",
    "applicants": 0
  }
];

export default vacanciesData;