const vacanciesData = [
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan",
    "Equipo TA": "OVH",
    "Gerencia": " Gerencia de Expansión Brownfield y Grandes Superficies",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Ricardo Awad/ Roberto Jimenez",
    "Cargo": "Gestor de Contratos (Confidencial)",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Carla Guerrero ",
    "Estado": "Cancelada",
    "TTF": 24,
    "Comentarios": "CO rechazada. Continúa búsqueda, Se cancela busqueda por que se junta cargo con el jefe de permisos de JP Almazora.",
    "Fecha Inicio Búsqueda": "2026-01-13",
    "Fecha Cubierta Búsqueda": "2026-02-13",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan",
    "Equipo TA": "OVH",
    "Gerencia": " Dirección Omnichannel & Digital Sales",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Jesús Fernández",
    "Cargo": "Jefe Comercial Media",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "Sebastián Farias",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "No - Nexus"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia Comercial Chile",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Tomás Neumann",
    "Cargo": "Jefe Comercial Autoplaza",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "Pedro Carcuro",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan",
    "Equipo TA": "OVH",
    "Gerencia": "Dirección Omnichannel & Digital Sales",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Jesús Fernández",
    "Cargo": "Jefe Comercial Media",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "No aplica",
    "Estado": "Activa",
    "TTF": 47,
    "Comentarios": "Quieren Ofertar a Daniela Reyes.(Entrevistadores: pancho martinez, jesus fernandez, ramiro, TA). Indefinido o plazo fijo.",
    "Fecha Inicio Búsqueda": "2026-01-18",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "No - Nexus"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan",
    "Equipo TA": "OVH",
    "Gerencia": "Dirección Omnichannel & Digital Sales",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Jesús Fernández",
    "Cargo": "Coordinador de Campañas",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Felipe Hurtado",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "No - Nexus"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Sofia Sinay",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia Divisional Chile",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Eduardo Mancilla",
    "Cargo": "Coordinadora Planificación Comercial ",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "No aplica",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Sofia Sinay",
    "Equipo TA": "OVH",
    "Gerencia": "Subgerencia Planificación Comercial",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Romina Mercado",
    "Cargo": "Jefe de Digitalización Comercial (confidencial)",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "Eduardo Mancilla",
    "Estado": "Activa",
    "TTF": 54,
    "Comentarios": "Hemos entrevistados varias candidatas, pero estamos revisando la posibilidad de traer a Valeria Keller Interna desde TI. Vamos a dejar en SB la vacante hasta revisar bien la estructura del equipo de Romina con Carlos Honorato.",
    "Fecha Inicio Búsqueda": "2026-01-08",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Francisca Rodriguez/ The Hunting",
    "Equipo TA": "Ejecutivo",
    "Gerencia": "Gerencia de Marketing y Experiencia",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Pilar Barriga",
    "Cargo": "Director de Marca",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "No aplica",
    "Estado": "Activa",
    "TTF": 57,
    "Comentarios": "Estamos revisando candidatos con Consultora the hunting, tenemos a Valentina Canepa que nos gusta mucho en proceso de entrevista final con Carlos Honorato la semana del 23 de Marzo.",
    "Fecha Inicio Búsqueda": "2026-01-05",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Pendiente"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Francisca Rodriguez/ The Hunting",
    "Equipo TA": "Ejecutivo",
    "Gerencia": "Gerencia de Marketing y Experiencia",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Pilar Barriga",
    "Cargo": "Director de Planeamiento y Control de Gestión de Marketing",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "No aplica",
    "Estado": "Activa",
    "TTF": 62,
    "Comentarios": "Estamos revisando candidatos con la Consultora the hunting. Hoy estamos viendo la posibilidad de promover a Carlos Esteban.",
    "Fecha Inicio Búsqueda": "2025-12-29",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Pendiente"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Jacinta Guzman",
    "Equipo TA": "OVH",
    "Gerencia": "Proyectos y Construcción",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Victor Pozo",
    "Cargo": "Administrador de Proyecto (confidencial)",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Katherina Veliz ",
    "Estado": "Activa",
    "TTF": 43,
    "Comentarios": "3 candidatos en proceso de entrevista por TA.",
    "Fecha Inicio Búsqueda": "2026-01-23",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Jacinta Guzman",
    "Equipo TA": "OVH",
    "Gerencia": "Proyectos y Construcción",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Victor Pozo",
    "Cargo": "Administrador de Proyecto (confidencial)",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Daniela Arancibia",
    "Estado": "Activa",
    "TTF": 43,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-01-23",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Antonia Rodríguez",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Pablo Ramos",
    "Cargo": "Ejecutivo Operacion Tiendas",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Cristopher Swet",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Antonia Rodríguez",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Felipe Alfaro",
    "Cargo": "Asistente de Mall",
    "Familia de cargo": "Administrativo",
    "¿A quién reemplaza?": "Ariel Paillaqueo",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Daniela Levill",
    "Equipo TA": "EJECUTIVA",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Marcela Rojas",
    "Cargo": "Subgerente Mall Tobalaba",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "Marcela Rojas",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Daniela Levill",
    "Equipo TA": "EJECUTIVA",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Ivana Paez",
    "Cargo": "Subgerente Mall ",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "Marcela Leiva",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Antonia Rodríguez",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Gabriela Aninat",
    "Cargo": "Asistente de Mall",
    "Familia de cargo": "Administrativo",
    "¿A quién reemplaza?": "Olaya FLores",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Antonia Rodríguez",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Cindy Gaete",
    "Cargo": "Ejecutivo Clientes",
    "Familia de cargo": "Tecnico/ Vendedor",
    "¿A quién reemplaza?": "Alvaro Aedo",
    "Estado": "Cerrada",
    "TTF": 33,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2025-11-19",
    "Fecha Cubierta Búsqueda": "2026-01-04",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Antonia Rodríguez",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Cindy Gaete",
    "Cargo": "Ejecutivo Clientes",
    "Familia de cargo": "Tecnico/ Vendedor",
    "¿A quién reemplaza?": "Mauricio Sepulveda",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Larraín",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Maria Gracia",
    "Cargo": "Jefe Sustentabilidad",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "Maria Jose Arancibia",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Seba Soto",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Maria Gracia",
    "Cargo": "Coordinador de Obras de Construcción",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Michael gonzales",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Antonia Rodríguez",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Karen Standen",
    "Cargo": "Ejecutivo Operacion Tiendas",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Edgardo Cavada",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Antonia Rodríguez",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Gabriela Garstaman",
    "Cargo": "Ejecutivo Operacion Tiendas",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Javier Mardones",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Pacual Prado",
    "Cargo": "Paisajista",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Belen Montoya",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "Se cerró internamente con bonos",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Melany Diaz",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Cindy Gaete",
    "Cargo": "Ejecutivo Clientes",
    "Familia de cargo": "Tecnico/ Vendedor",
    "¿A quién reemplaza?": "Florencia Riveros",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Maria Jesus Lagos",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Mauricio Vargas",
    "Cargo": "Jefe Zonal de Operacion",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "Christian Martinez",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Maria Gracia",
    "Cargo": "Controller Cumplimiento Ambiental",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Denise Tijoux",
    "Estado": "Activa",
    "TTF": 41,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-01-27",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Camila Rivas",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Matias Larrain",
    "Cargo": "Ejecutivo Operacion Tiendas (confidencial)",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Valentina Carcamo",
    "Estado": "Activa",
    "TTF": 36,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-02-03",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Camila Rivas",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Pablo Berndt",
    "Cargo": "Ejecutivo Operacion Tiendas (confidencial)",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Mauricio Alvarez",
    "Estado": "Cerrada",
    "TTF": 26,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-02-03",
    "Fecha Cubierta Búsqueda": "2026-03-10",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Camila Rivas",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Marcela Rojas",
    "Cargo": "Tecnico en Prevención",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "-",
    "Estado": "Cerrada",
    "TTF": 34,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-02-03",
    "Fecha Cubierta Búsqueda": "2026-03-20",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Camila Rivas",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Brunilda Gilardoni",
    "Cargo": "Ejecutivo Operacion Tiendas",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Paulina Estrada",
    "Estado": "Activa",
    "TTF": 13,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-06",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Camila Rivas",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Matias Larrain",
    "Cargo": "Ejecutivo Clientes",
    "Familia de cargo": "Tecnico/ Vendedor",
    "¿A quién reemplaza?": "Francisca Rosas",
    "Estado": "Cerrada",
    "TTF": 37,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-01-29",
    "Fecha Cubierta Búsqueda": "2026-03-20",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Camila Rivas",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Alfonso Adrover",
    "Cargo": "Ejecutivo Clientes",
    "Familia de cargo": "Tecnico/ Vendedor",
    "¿A quién reemplaza?": "Camila Miranda",
    "Estado": "Cerrada",
    "TTF": 37,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-01-29",
    "Fecha Cubierta Búsqueda": "2026-03-20",
    "Forecast": ""
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Trinidad Paz",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Francisco Eskenazi",
    "Cargo": "Ejecutivo Clientes",
    "Familia de cargo": "Tecnico/ Vendedor",
    "¿A quién reemplaza?": "Maira Ipinza",
    "Estado": "Cerrada",
    "TTF": 36,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-01-30",
    "Fecha Cubierta Búsqueda": "2026-03-20",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Trinidad Paz",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Marcela Leiva",
    "Cargo": "Jefe Operaciones Comerciales",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "Jorge Chavez",
    "Estado": "Cerrada",
    "TTF": 19,
    "Comentarios": "Movimiento Interno",
    "Fecha Inicio Búsqueda": "2026-02-03",
    "Fecha Cubierta Búsqueda": "2026-02-28",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Trinidad Paz",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Karen Standen",
    "Cargo": "Jefe Operaciones Comerciales",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "Paz Soto",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "María Jesús Jiménez ",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Estregia y Performance ",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Carolina Brahm",
    "Cargo": "Analista Control De Gestion",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Martin Seguel",
    "Estado": "Cerrada",
    "TTF": 26,
    "Comentarios": "Nelson candidato interno / ya tenemos carta oferta falta enviarsela a Jose Jordan ",
    "Fecha Inicio Búsqueda": "2026-01-29",
    "Fecha Cubierta Búsqueda": "2026-03-05",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Trinidad Paz",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Marcela Leiva",
    "Cargo": "Asistente de Mall",
    "Familia de cargo": "Administrativo",
    "¿A quién reemplaza?": "Maria Isabel Abarca",
    "Estado": "Cerrada",
    "TTF": 17,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-01-28",
    "Fecha Cubierta Búsqueda": "2026-02-19",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Andre Delaveau",
    "Cargo": "Ejecutivo Revisor de Especialidades",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Miguel Ramirez",
    "Estado": "Activa",
    "TTF": 31,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-02-10",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Melany Diaz",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Cecilia Diaz",
    "Cargo": "Asistente de Mall",
    "Familia de cargo": "Administrativo",
    "¿A quién reemplaza?": "Pia Delgado",
    "Estado": "Cerrada",
    "TTF": 22,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-01-05",
    "Fecha Cubierta Búsqueda": "2026-02-03",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Maria Esperanza",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Camilo Gonzalez",
    "Cargo": "Ejecutivo Clientes",
    "Familia de cargo": "Tecnico/ Vendedor",
    "¿A quién reemplaza?": "Giovanni Fernandez",
    "Estado": "Cerrada",
    "TTF": 30,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-01-28",
    "Fecha Cubierta Búsqueda": "2026-03-10",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Trinidad Paz",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Cesar Villouta",
    "Cargo": "Ejecutivo Clientes",
    "Familia de cargo": "Tecnico/ Vendedor",
    "¿A quién reemplaza?": "Nataly Delgado",
    "Estado": "Cerrada",
    "TTF": 16,
    "Comentarios": "Casi listo con un referido",
    "Fecha Inicio Búsqueda": "2026-01-29",
    "Fecha Cubierta Búsqueda": "2026-02-19",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Maria Esperanza",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Mariana Lasalle",
    "Cargo": "Ejecutivo Clientes",
    "Familia de cargo": "Tecnico/ Vendedor",
    "¿A quién reemplaza?": "Mauricio Etcheverry",
    "Estado": "Activa",
    "TTF": 40,
    "Comentarios": "Harta postulación, comienza selección de terna",
    "Fecha Inicio Búsqueda": "2026-01-28",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Trinidad Paz",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Brunilda Gilardoni",
    "Cargo": "Ejecutivo Clientes",
    "Familia de cargo": "Tecnico/ Vendedor",
    "¿A quién reemplaza?": "Lienchen Friz",
    "Estado": "Activa",
    "TTF": 39,
    "Comentarios": "2 Candidatas en proceso de entrevista (entrevistas 09-10/02)",
    "Fecha Inicio Búsqueda": "2026-01-29",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Trinidad Paz",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Mauricio Maldonado",
    "Cargo": "Prevencionista de Riesgos",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Joel Osses",
    "Estado": "Cerrada",
    "TTF": 35,
    "Comentarios": "13 postulaciones. pero nada bueno",
    "Fecha Inicio Búsqueda": "2026-01-27",
    "Fecha Cubierta Búsqueda": "2026-03-16",
    "Forecast": "Si"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Trinidad Paz",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Raul Perez",
    "Cargo": "Prevencionista de Riesgos",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Fernanda Rojas",
    "Estado": "Activa",
    "TTF": 40,
    "Comentarios": "2 candidatos que van a ser evaluados mañana 06-02. Uno es interno que esta terminando reemplazo y el otro externo. ",
    "Fecha Inicio Búsqueda": "2026-01-28",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Betsabet Carrasco ",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Tecnología ",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Adrian Hernandez ",
    "Cargo": "Data Engineer",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Felipe Cortés",
    "Estado": "Activa",
    "TTF": 91,
    "Comentarios": "09-02-2026 reunión con adrian, parte proceso de cero, se cae por contraoferta. Hoy jueves 12 envia mas cv. Modalidad de trabajo y renta (revisar modalidad para tecnología) Se cae candidato. Ver con adrian los proximos cv que envio el 10-03. Esta participando cesar araya en el proceso, han rechazado 2 CO en este proceso. Cesar va a entrevistar nuevos candidatos el lunes/Martes/Miercoles. ",
    "Fecha Inicio Búsqueda": "2025-11-18",
    "Fecha Cubierta Búsqueda": "2026-02-26",
    "Forecast": "Si"
  },
  {
    "HRBP": "María Jesús Jiménez ",
    "País": "Chile",
    "Coordinador TA Responsable": "Betsabet Carrasco ",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Tecnología ",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Felipe Nuñez ",
    "Cargo": "Jefe de Proyecto ",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "Leonardo Fernandez ",
    "Estado": "Cerrada",
    "TTF": 20,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2025-12-12",
    "Fecha Cubierta Búsqueda": "2026-01-08",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Camila Rivas",
    "Equipo TA": "OVH",
    "Gerencia": "Proyecto SAP",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Alejandro Peraza (Por Ahora)",
    "Cargo": "Arquitecto Sap * Hana ",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Posición nueva ",
    "Estado": "Activa",
    "TTF": 91,
    "Comentarios": "jhony muñoz el viernes, esta a espera de feeback de la entrevista. ",
    "Fecha Inicio Búsqueda": "2025-11-18",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "María Jesús Jiménez ",
    "País": "Chile",
    "Coordinador TA Responsable": "Gabriela ",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Tecnología ",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Andrea Casas",
    "Cargo": "Jefe FICO",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "Gleeny Colmenares ",
    "Estado": "Cancelada",
    "TTF": -32904,
    "Comentarios": "Proceso se abre nuevamente. ",
    "Fecha Inicio Búsqueda": "2026-02-12",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "No"
  },
  {
    "HRBP": "María Jesús Jiménez ",
    "País": "Chile",
    "Coordinador TA Responsable": "Javiera Nuñez ",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Tecnología ",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Javier Alarcón ",
    "Cargo": "Senior Data Architect ",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Iván Carrizo ",
    "Estado": "Cancelada",
    "TTF": -32790,
    "Comentarios": "Javier Alarcón no a contestado por cv enviados hace mas de 2 semanas. Revisar que pasa con el proceso. ",
    "Fecha Inicio Búsqueda": "2025-09-05",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefine Jordan ",
    "Equipo TA": "OVH",
    "Gerencia": "Proyecto SAP",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Alejandro Peraza ",
    "Cargo": "Lider de Ambientes Sap ",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "Posición nueva ",
    "Estado": "Activa",
    "TTF": 87,
    "Comentarios": "entre miercoles 11 y jueves 12 en entrevista con alejandro peraza. Eduardo azocar y wilmer figueroa ",
    "Fecha Inicio Búsqueda": "2025-11-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Javiera Nuñez ",
    "Equipo TA": "OVH",
    "Gerencia": "Proyecto SAP",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Alejandro Peraza",
    "Cargo": "Technical Lead Sap",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "Posición nueva ",
    "Estado": "Activa",
    "TTF": -182,
    "Comentarios": "Finalista estaba listo y se bajo el candidato dado que Andrea se bajo",
    "Fecha Inicio Búsqueda": "2026-12-02",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "No * es sap?"
  },
  {
    "HRBP": "María Jesús Jiménez ",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan ",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia Legal ",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "M Pia Herrera ",
    "Cargo": "Analista de Cumplimiento ",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Confidencial ",
    "Estado": "Stand By",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "María Jesús Jiménez ",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan ",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia Estrategia y Performance",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Carolina Henriquez  ",
    "Cargo": "Analista Control de Gestión ",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Karen Sepulveda",
    "Estado": "Activa",
    "TTF": 52,
    "Comentarios": "Matias Ramos / ver opción de 50 mil pesos mas. ",
    "Fecha Inicio Búsqueda": "2026-01-12",
    "Fecha Cubierta Búsqueda": "2026-03-05",
    "Forecast": "Si"
  },
  {
    "HRBP": "María Jesús Jiménez ",
    "País": "Chile",
    "Coordinador TA Responsable": "Francisca Rodriguez ",
    "Equipo TA": "EJECUTIVA",
    "Gerencia": "Proyecto SAP",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Gonzalo Estay y Paula Jara ",
    "Cargo": "Gerente de Proyecto SAP",
    "Familia de cargo": "Top Management ",
    "¿A quién reemplaza?": "Posición nueva ",
    "Estado": "Cancelada",
    "TTF": 0,
    "Comentarios": "Iván es el candidato preseleccionado, ya fue entrevistado por Gonzalo, Paula y Derek. Jueves pm entrevista M Jesus Jimenez para ver si cerrar con el. ",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "María Jesús Jiménez ",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan ",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Estrategia y Performance",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Nicolás Ruiz ",
    "Cargo": "Jefe de Inversiones ",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "Nicolas Ruiz",
    "Estado": "Cerrada",
    "TTF": 21,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-01-16",
    "Fecha Cubierta Búsqueda": "2026-02-15",
    "Forecast": "Si"
  },
  {
    "HRBP": "María Jesús Jiménez ",
    "País": "Chile",
    "Coordinador TA Responsable": "KF",
    "Equipo TA": "EJECUTIVA",
    "Gerencia": "Gerencia Legal ",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "M Pía Herrera ",
    "Cargo": "Subgerente de Riesgo ",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "Juliane Guanaes ",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "Pablo fue ofertado hoy 03-02-2026 a espera de respuesta del candidato. Pasa a ser Director de Riesgo reportando a Hernán Silva ",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Betzabet Carrasco",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Tecnología ",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Felipe Nuñez ",
    "Cargo": "Tech Lead ",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "Posición Nueva ",
    "Estado": "Activa",
    "TTF": 47,
    "Comentarios": "Primero entrevista técnica, y luego betzabet, 3 personas en entrevista. ",
    "Fecha Inicio Búsqueda": "2026-01-19",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "María Jesús Jiménez ",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan ",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia Estrategia y Performance",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Carolina Henriquez  ",
    "Cargo": "Analista Control de Gestión ",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Ninoska Araneda",
    "Estado": "Activa",
    "TTF": 31,
    "Comentarios": "viene de falabella inmobiliario ",
    "Fecha Inicio Búsqueda": "2026-02-10",
    "Fecha Cubierta Búsqueda": "2026-03-05",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Margarita Araneda",
    "Equipo TA": "Ejecutivo",
    "Gerencia": "Proyectos y Construcción",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Daniel Bravo",
    "Cargo": "Director de Construcción - Concepción",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "No aplica",
    "Estado": "Cerrada",
    "TTF": 41,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2025-12-09",
    "Fecha Cubierta Búsqueda": "2026-02-03",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Margarita Araneda",
    "Equipo TA": "Ejecutivo",
    "Gerencia": "Proyectos y Construcción",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Daniel Bravo",
    "Cargo": "Director de Construcción - Santiago",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "No aplica",
    "Estado": "Cerrada",
    "TTF": 41,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2025-12-09",
    "Fecha Cubierta Búsqueda": "2026-02-03",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Francisca Rodriguez",
    "Equipo TA": "Ejecutivo",
    "Gerencia": "Proyectos y Construcción",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Daniel Bravo",
    "Cargo": "Director de Construcción Chile",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "No aplica",
    "Estado": "Activa",
    "TTF": 38,
    "Comentarios": "Revisando nuevos candidatos.",
    "Fecha Inicio Búsqueda": "2026-01-30",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Expansión Brownfield y Grandes Superficies",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Juan Pablo Almazora",
    "Cargo": "Jefe Gestión Permisos y Gestión Vial",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Activa",
    "TTF": 57,
    "Comentarios": "Proceso de Entrevista desde TA.",
    "Fecha Inicio Búsqueda": "2026-01-05",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Renan Quispe",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia Comercial Perú",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Kristine Plenge",
    "Cargo": "Practicante Profesional",
    "Familia de cargo": "Practicante",
    "¿A quién reemplaza?": "Pablo del Aguila",
    "Estado": "Cerrada",
    "TTF": 15,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2025-12-03",
    "Fecha Cubierta Búsqueda": "2025-12-23",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Renan Quispe",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia Comercial Perú",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Anggela Pérez",
    "Cargo": "Practicante Profesional",
    "Familia de cargo": "Practicante",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Cerrada",
    "TTF": 3,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2025-12-19",
    "Fecha Cubierta Búsqueda": "2025-12-23",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "-",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Andres Farro",
    "Cargo": "Ejecutivo Operacion Tienda",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Katherine Ordaya",
    "Estado": "Cerrada",
    "TTF": 0,
    "Comentarios": "Pasa de OP Atocongo a Mallplaza Angamos",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Brissa Pósito",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Cesli Carhuamaca",
    "Cargo": "Ejecutivo Operacion Tienda",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Carla Franco",
    "Estado": "Cerrada",
    "TTF": 31,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2025-11-24",
    "Fecha Cubierta Búsqueda": "2026-01-05",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Daniella Matta",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia Comercial Perú",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Andrea Luna",
    "Cargo": "Ejecutivo Comercial Jr.",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Paola Juarez",
    "Estado": "Cerrada",
    "TTF": 31,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2025-11-10",
    "Fecha Cubierta Búsqueda": "2025-12-22",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Irwin Paulino",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia Regional de Tecnología",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Lucianne Giha",
    "Cargo": "Practicante Profesional",
    "Familia de cargo": "Practicante",
    "¿A quién reemplaza?": "No aplica",
    "Estado": "Cerrada",
    "TTF": 15,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2025-12-24",
    "Fecha Cubierta Búsqueda": "2026-01-13",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Irwin Paulino",
    "Equipo TA": "Operaciones",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Giancarlo Centomini",
    "Cargo": "Ejecutivo de Clientes y Marketing",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Pamela Murguia",
    "Estado": "Cerrada",
    "TTF": 29,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2025-12-24",
    "Fecha Cubierta Búsqueda": "2026-02-02",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Fernanda Armas",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Estrategia y Performance",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Alvaro Sanchez",
    "Cargo": "Analista de Gestión de Proyectos",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Cristian Serrano",
    "Estado": "Cerrada",
    "TTF": 40,
    "Comentarios": "Movimiento intercompany: Sodimac a Mallplaza",
    "Fecha Inicio Búsqueda": "2025-12-11",
    "Fecha Cubierta Búsqueda": "2026-02-04",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Gabriela Vera Tudela",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia Comercial Perú",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Anggela Pérez",
    "Cargo": "Ejecutivo Comercial Senior (confidencial)",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Confidencial ",
    "Estado": "Cerrada",
    "TTF": 55,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2025-12-18",
    "Fecha Cubierta Búsqueda": "2026-03-04",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Gabriela Vera Tudela",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia Comercial Perú",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Anggela Pérez",
    "Cargo": "Ejecutivo Comercial (confidencial)",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Lusiane Wetzell",
    "Estado": "Cerrada",
    "TTF": 65,
    "Comentarios": "Crecimiento Interno",
    "Fecha Inicio Búsqueda": "2025-12-18",
    "Fecha Cubierta Búsqueda": "2026-03-18",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Denisse Guarniz",
    "Equipo TA": "Operaciones",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Sergio Chamochumbi",
    "Cargo": "Director de Mall",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "Andres Farro",
    "Estado": "Cerrada",
    "TTF": 52,
    "Comentarios": "Crecimiento Interno",
    "Fecha Inicio Búsqueda": "2025-12-29",
    "Fecha Cubierta Búsqueda": "2026-03-10",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Gabriela Vera Tudela",
    "Equipo TA": "Operaciones",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Pilar Arellano",
    "Cargo": "Adminsitrador de Centro Comercial",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "Cinthia García",
    "Estado": "Activa",
    "TTF": 51,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-01-13",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Gabriela Vera Tudela",
    "Equipo TA": "Operaciones",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Pilar Arellano",
    "Cargo": "Adminsitrador de Centro Comercial",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "Paul Alvia",
    "Estado": "Activa",
    "TTF": 51,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-01-13",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Denisse Guarniz",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Sergio Chamochumbi",
    "Cargo": "Jefe de Prevención (confidencial)",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Confidencial ",
    "Estado": "Cerrada",
    "TTF": 46,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-01-16",
    "Fecha Cubierta Búsqueda": "2026-03-20",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Denisse Guarniz",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Sergio Chamochumbi",
    "Cargo": "Coordinador de Energía (confiendencial)",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Confidencial ",
    "Estado": "Cerrada",
    "TTF": 40,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-01-16",
    "Fecha Cubierta Búsqueda": "2026-03-12",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Denisse Guarniz",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Maria Grazia Mogrovejo",
    "Cargo": "Ejecutivo Revisor de Especialidades",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Cerrada",
    "TTF": 43,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-01-22",
    "Fecha Cubierta Búsqueda": "2026-03-23",
    "Forecast": "No"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Denisse Guarniz",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Maria Grazia Mogrovejo",
    "Cargo": "Ejecutivo Revisor de Especialidades",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Activa",
    "TTF": 44,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-01-22",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "No"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Brissa Pósito",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Administración",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Jose Cabanillas",
    "Cargo": "Analista de Cobranzas",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Karol Gordillo",
    "Estado": "Cerrada",
    "TTF": 28,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-01-29",
    "Fecha Cubierta Búsqueda": "2026-03-09",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Daniella Matta",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Administración",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Paula Beltran",
    "Cargo": "Analista de Control de Gestion",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Clyde Farias",
    "Estado": "Activa",
    "TTF": 33,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-02-06",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Karolina Rojas",
    "Equipo TA": "Operaciones",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Andres Farro",
    "Cargo": "Ejecutivo de Clientes y Marketing",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Beatriz Castro",
    "Estado": "Cerrada",
    "TTF": 31,
    "Comentarios": "Pasa de MP Arequipa a MP Angamos",
    "Fecha Inicio Búsqueda": "2025-12-30",
    "Fecha Cubierta Búsqueda": "2026-02-10",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Perú",
    "Coordinador TA Responsable": "Francisca Rodriguez",
    "Equipo TA": "Ejecutivo",
    "Gerencia": "Proyectos y Construcción",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Daniel Bravo",
    "Cargo": "Director de Proyectos",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "Reemplazo Confidencial",
    "Estado": "Cerrada",
    "TTF": 3,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-02-02",
    "Fecha Cubierta Búsqueda": "2026-02-04",
    "Forecast": "No sé"
  },
  {
    "HRBP": "Laura Camargo",
    "País": "Colombia",
    "Coordinador TA Responsable": "Leidy Lorena González",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia Divisional Chile y Colombia ",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Marcela Galindo",
    "Cargo": "Ejecutiva Espacios Publicitarios",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Camila Lora",
    "Estado": "Cerrada",
    "TTF": 21,
    "Comentarios": "Ingreso",
    "Fecha Inicio Búsqueda": "2026-01-05",
    "Fecha Cubierta Búsqueda": "2026-02-02",
    "Forecast": "SI"
  },
  {
    "HRBP": "Laura Camargo",
    "País": "Colombia",
    "Coordinador TA Responsable": "Leidy Lorena González",
    "Equipo TA": "OVH",
    "Gerencia": "Subgerencia Mallplaza Manizales",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Laura Camargo",
    "Cargo": "Ejecutiva de Ventas MNZ",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "N/A",
    "Estado": "Cerrada",
    "TTF": 15,
    "Comentarios": "Ingreso",
    "Fecha Inicio Búsqueda": "2026-01-05",
    "Fecha Cubierta Búsqueda": "2026-01-23",
    "Forecast": "SI"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Margarita Araneda",
    "Equipo TA": "Ejecutivo",
    "Gerencia": "Proyectos y Construcción ",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Daniel Bravo",
    "Cargo": "Director de Construcción La Serena",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "No aplica",
    "Estado": "Cerrada",
    "TTF": 39,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2025-12-09",
    "Fecha Cubierta Búsqueda": "2026-01-30",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Maria Jesus Lagos",
    "Equipo TA": "OVH",
    "Gerencia": "Marketing y Experience",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Maria Francisca Guerra",
    "Cargo": "Jefe de Marketing Chile",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "",
    "Estado": "Cerrada",
    "TTF": 15,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2025-12-16",
    "Fecha Cubierta Búsqueda": "2026-01-05",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordán",
    "Equipo TA": "OVH",
    "Gerencia": "Personas",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Leonardo Valiente",
    "Cargo": "Analista Control de Nómina y Procesos",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Javiera Reyes",
    "Estado": "Cerrada",
    "TTF": 19,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2025-12-18",
    "Fecha Cubierta Búsqueda": "2026-01-13",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Perú",
    "Coordinador TA Responsable": "Francisca Rodriguez",
    "Equipo TA": "Ejecutivo",
    "Gerencia": "Proyectos y Construcción",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Daniel Bravo",
    "Cargo": "Director de Proyectos - Piura",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "Nueva vacante",
    "Estado": "Cerrada",
    "TTF": 38,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2025-12-17",
    "Fecha Cubierta Búsqueda": "2026-02-06",
    "Forecast": "No sé"
  },
  {
    "HRBP": "Laura Camargo",
    "País": "Colombia",
    "Coordinador TA Responsable": "Lina Casas",
    "Equipo TA": "OVH",
    "Gerencia": "Proyectos y Construcciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Daniel Bravo",
    "Cargo": "Lider de Arquitectura- Reemplazp Licencia Materna",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Maria Nova",
    "Estado": "Cerrada",
    "TTF": 33,
    "Comentarios": "Ingreso",
    "Fecha Inicio Búsqueda": "2026-01-06",
    "Fecha Cubierta Búsqueda": "2026-02-19",
    "Forecast": "SI"
  },
  {
    "HRBP": "Laura Camargo",
    "País": "Colombia",
    "Coordinador TA Responsable": "Maira Gonzalez",
    "Equipo TA": "OVH",
    "Gerencia": "Subgerencia Legal Colombia",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Daniela Gonzalez",
    "Cargo": "Practicante Universitario",
    "Familia de cargo": "Practicante",
    "¿A quién reemplaza?": "Ana Diaz",
    "Estado": "Cerrada",
    "TTF": 13,
    "Comentarios": "Ingreso",
    "Fecha Inicio Búsqueda": "2026-01-15",
    "Fecha Cubierta Búsqueda": "2026-02-02",
    "Forecast": "SI"
  },
  {
    "HRBP": "Laura Camargo",
    "País": "Colombia",
    "Coordinador TA Responsable": "Leidy Lorena González",
    "Equipo TA": "OVH",
    "Gerencia": "Subgerencia Mallplaza Cali",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Juan Manuel Rengifo",
    "Cargo": "Ejecutiva de Clientes CAL",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Valeria Esquivel",
    "Estado": "Cerrada",
    "TTF": 27,
    "Comentarios": "Contratación",
    "Fecha Inicio Búsqueda": "2026-02-03",
    "Fecha Cubierta Búsqueda": "2026-03-11",
    "Forecast": "SI"
  },
  {
    "HRBP": "Laura Camargo",
    "País": "Colombia",
    "Coordinador TA Responsable": "Lina Casas",
    "Equipo TA": "OVH",
    "Gerencia": "Subgerencia Mallplaza Cartagena",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Marcela Campo",
    "Cargo": "Aprendiz Sena CTG",
    "Familia de cargo": "Practicante",
    "¿A quién reemplaza?": "Ana Carlota",
    "Estado": "Cerrada",
    "TTF": 18,
    "Comentarios": "Ingreso",
    "Fecha Inicio Búsqueda": "2026-01-02",
    "Fecha Cubierta Búsqueda": "2026-01-27",
    "Forecast": "SI"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Camila Rivas",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Pablo Berndt",
    "Cargo": "Product Manager",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Constanza Ruiz",
    "Estado": "Cerrada",
    "TTF": 25,
    "Comentarios": "Carta Oerta Pendiente",
    "Fecha Inicio Búsqueda": "2026-02-16",
    "Fecha Cubierta Búsqueda": "2026-03-20",
    "Forecast": ""
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Camila Rivas",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Pablo Berndt",
    "Cargo": "Asistente de Mall",
    "Familia de cargo": "Administrativo",
    "¿A quién reemplaza?": "Francisca Chavez",
    "Estado": "Activa",
    "TTF": 27,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-02-16",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Camila Rivas",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Gabriela Garstman",
    "Cargo": "Asistente de Mall",
    "Familia de cargo": "Administrativo",
    "¿A quién reemplaza?": "Francisca Aguila",
    "Estado": "Activa",
    "TTF": 27,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-02-16",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Camila Rivas",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Karen Standen",
    "Cargo": "Asistente de Mall",
    "Familia de cargo": "Administrativo",
    "¿A quién reemplaza?": "Paola Ramirez",
    "Estado": "Activa",
    "TTF": 27,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-02-16",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "Melany Diaz",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Maria Cecilia Diaz",
    "Cargo": "Asistente de Mall",
    "Familia de cargo": "Administrativo",
    "¿A quién reemplaza?": "Irene Alvarez",
    "Estado": "Cerrada",
    "TTF": 24,
    "Comentarios": "Pendiente Carta Oferta",
    "Fecha Inicio Búsqueda": "2026-02-17",
    "Fecha Cubierta Búsqueda": "2026-03-20",
    "Forecast": ""
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Tania Guerra",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Administración",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Macarena Urrutia",
    "Cargo": "Asistente de Gerencia",
    "Familia de cargo": "Administrativo",
    "¿A quién reemplaza?": "Madelen Tello",
    "Estado": "Activa",
    "TTF": 27,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-02-16",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Perú",
    "Coordinador TA Responsable": "Francisca Rodriguez",
    "Equipo TA": "OVH",
    "Gerencia": "Proyectos y Construcción",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Daniel Bravo",
    "Cargo": "Director de Construcción Perú",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Activa",
    "TTF": 32932,
    "Comentarios": "Rechaza CO. Revisando sueldo nuevamente y viendo propuesta de assesment.",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Daniella Matta",
    "Equipo TA": "Operaciones",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Ricardo Fuertes",
    "Cargo": "Ejecutivo de Clientes y Marketing",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Mirella Alvarez",
    "Estado": "Activa",
    "TTF": 19,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-02-26",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Maria Jose Carrizo",
    "Equipo TA": "Ejecutivo",
    "Gerencia": "Gerencia de Marketing y Experiencia",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Pilar Barriga",
    "Cargo": "Directora de Experiencia",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "Catalina Cruz",
    "Estado": "Cerrada",
    "TTF": 14,
    "Comentarios": "Cerrada con promoción interna",
    "Fecha Inicio Búsqueda": "2025-12-19",
    "Fecha Cubierta Búsqueda": "2026-01-07",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Maria Jose Carrizo",
    "Equipo TA": "Ejecutivo",
    "Gerencia": "Gerencia de Marketing y Experiencia",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Pilar Barriga",
    "Cargo": "Directora de Marketing Chile",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "",
    "Estado": "Cerrada",
    "TTF": 33,
    "Comentarios": "Referida de Pilar Barriga.",
    "Fecha Inicio Búsqueda": "2025-11-20",
    "Fecha Cubierta Búsqueda": "2026-01-05",
    "Forecast": "Si"
  },
  {
    "HRBP": "María Jesús Jiménez ",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan ",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia Estrategia y Performance",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Carolina Brahm",
    "Cargo": "Analista Control de Gestión ",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Martin Valenzuela ",
    "Estado": "Activa",
    "TTF": 14,
    "Comentarios": "Jose J entrevista jueves y viernes y les avisa como le va y avanzamos con Fabian. ",
    "Fecha Inicio Búsqueda": "2026-03-05",
    "Fecha Cubierta Búsqueda": "2026-03-10",
    "Forecast": ""
  },
  {
    "HRBP": "María Jesús Jiménez ",
    "País": "Chile",
    "Coordinador TA Responsable": "Camila Rivas",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Administración ",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Carlos Martinez ",
    "Cargo": "Analista Aseguramiento de Ingreso",
    "Familia de cargo": "Especialista/ Profesional",
    "¿A quién reemplaza?": "Scarlett Rios ",
    "Estado": "Activa",
    "TTF": 17,
    "Comentarios": "terna 1, quiere dejar a uno en veremos. Lunes presencial entrevista segunda terna. ",
    "Fecha Inicio Búsqueda": "2026-03-02",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Sofia Fusch",
    "Equipo TA": "Ejecutivo",
    "Gerencia": "Gerencia de Expansión Brownfield y Grandes Superficies",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Ricardo Awad",
    "Cargo": "Subgerente de Brownfield",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Activa",
    "TTF": 7,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-16",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Pendiente",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Expansión Brownfield y Grandes Superficies",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Paloma Cuesta",
    "Cargo": "Practicante",
    "Familia de cargo": "Practicante",
    "¿A quién reemplaza?": "",
    "Estado": "Activa",
    "TTF": 22,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-02-23",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Pendiente",
    "Equipo TA": "OVH",
    "Gerencia": "Desarrollo de Nuevos Negocios",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Consuelo Zuñiga",
    "Cargo": "PM",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Valentina Neuwman",
    "Estado": "Activa",
    "TTF": 22,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-02-23",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Pendiente",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Marketing y Experiencia",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Florencia Acosta",
    "Cargo": "Practicante",
    "Familia de cargo": "Practicante",
    "¿A quién reemplaza?": "",
    "Estado": "Activa",
    "TTF": 22,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-02-23",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Isidora Allendes",
    "Equipo TA": "Ejecutivo",
    "Gerencia": "Desarrollo de Nuevos Negocios",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Sebastian Schwerter",
    "Cargo": "Subgerente de Exploración",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "N/A",
    "Estado": "Activa",
    "TTF": 22,
    "Comentarios": "1 Candidato e entrevista con Rodrigo Alcalde, y otros en proceso para activar terna final.",
    "Fecha Inicio Búsqueda": "2026-02-23",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "",
    "País": "",
    "Coordinador TA Responsable": "",
    "Equipo TA": "",
    "Gerencia": "",
    "Motivo de Busqueda": "",
    "Líder": "",
    "Cargo": "4 administradores*",
    "Familia de cargo": "",
    "¿A quién reemplaza?": "",
    "Estado": "",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "",
    "País": "",
    "Coordinador TA Responsable": "",
    "Equipo TA": "",
    "Gerencia": "",
    "Motivo de Busqueda": "",
    "Líder": "",
    "Cargo": "Director de Lima",
    "Familia de cargo": "",
    "¿A quién reemplaza?": "",
    "Estado": "",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "",
    "País": "",
    "Coordinador TA Responsable": "",
    "Equipo TA": "",
    "Gerencia": "",
    "Motivo de Busqueda": "",
    "Líder": "",
    "Cargo": "3 adm peru",
    "Familia de cargo": "",
    "¿A quién reemplaza?": "",
    "Estado": "",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan",
    "Equipo TA": "OVH",
    "Gerencia": "Proyectos y Construcción",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Cristian Hasenhor",
    "Cargo": "Arquitecto",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Activa",
    "TTF": 16,
    "Comentarios": "En revisión de CV´s",
    "Fecha Inicio Búsqueda": "2026-02-23",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Sofia Sinay",
    "Equipo TA": "OVH",
    "Gerencia": "Talento y Cultura",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Andrea Pizarro",
    "Cargo": "Jefe de DO",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Cerrada",
    "TTF": 19,
    "Comentarios": "En CO - Javiera Abufom / a la espera de respuesta",
    "Fecha Inicio Búsqueda": "2026-02-18",
    "Fecha Cubierta Búsqueda": "2026-03-16",
    "Forecast": "Si"
  },
  {
    "HRBP": "Laura Camargo",
    "País": "Colombia",
    "Coordinador TA Responsable": "Maira Gonzalez",
    "Equipo TA": "OVH",
    "Gerencia": "Proyectos y Construcciones",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "John Amortegui",
    "Cargo": "Aprendiz Sena PROYECTOS",
    "Familia de cargo": "Practicante",
    "¿A quién reemplaza?": "N/A",
    "Estado": "Activa",
    "TTF": 22,
    "Comentarios": "Fase final entrevista",
    "Fecha Inicio Búsqueda": "2026-02-23",
    "Fecha Cubierta Búsqueda": "2026-02-19",
    "Forecast": "SI"
  },
  {
    "HRBP": "Laura Camargo",
    "País": "Colombia",
    "Coordinador TA Responsable": "Lina Casas",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia Comercial",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Laura Morales",
    "Cargo": "Analista de Gestion Comercial",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Alejandro Rios",
    "Estado": "Activa",
    "TTF": 32932,
    "Comentarios": "Pruebas",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "SI"
  },
  {
    "HRBP": "María Jesús Jiménez ",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan ",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Finanzas y Relación con Inversionistas",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Sebastian Mohr",
    "Cargo": "Analista de Finanzas ",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Tomas Villalobos",
    "Estado": "Activa",
    "TTF": 32932,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "María Jesús Jiménez ",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan ",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia Estrategia y Performance",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Felipe Sandoval ",
    "Cargo": "Analista Financiero",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "",
    "Estado": "Activa",
    "TTF": 32932,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "",
    "Equipo TA": "",
    "Gerencia": "",
    "Motivo de Busqueda": "",
    "Líder": "",
    "Cargo": "",
    "Familia de cargo": "",
    "¿A quién reemplaza?": "",
    "Estado": "",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "",
    "Equipo TA": "",
    "Gerencia": "",
    "Motivo de Busqueda": "",
    "Líder": "",
    "Cargo": "",
    "Familia de cargo": "",
    "¿A quién reemplaza?": "",
    "Estado": "",
    "TTF": 0,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Josefina Jordan",
    "Equipo TA": "OVH",
    "Gerencia": "Proyectos y Construcción",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Cristian Hasenhor",
    "Cargo": "Arquitecto",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Activa",
    "TTF": 22,
    "Comentarios": "En revisión de CV´s",
    "Fecha Inicio Búsqueda": "2026-02-23",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Sofia Fusch",
    "Equipo TA": "Ejecutivo",
    "Gerencia": "Brownfield y Grandes Superficies",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Ricardo Awad",
    "Cargo": "Subgerente de Brownfield Chile",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Activa",
    "TTF": 7,
    "Comentarios": "Activando el proceso",
    "Fecha Inicio Búsqueda": "2026-03-16",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Jacinta Guzman",
    "Equipo TA": "OVH",
    "Gerencia": "Proyectos y Construcción",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Jaime Bastiass",
    "Cargo": "Administrador de Obra ",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Activa",
    "TTF": 11,
    "Comentarios": "Proceso CO a Daniela Sanchez",
    "Fecha Inicio Búsqueda": "2026-03-10",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Camila Rivas",
    "Equipo TA": "OVH",
    "Gerencia": "Proyectos y Construcción",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Edison Belmar",
    "Cargo": "Administrador de Obra La serena",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Activa",
    "TTF": 11,
    "Comentarios": "En revisión de CV´s",
    "Fecha Inicio Búsqueda": "2026-03-10",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Camila Rivas",
    "Equipo TA": "OVH",
    "Gerencia": "Proyectos y Construcción",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Jaime Bastiass",
    "Cargo": "Administrador de Obra Oeste",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Activa",
    "TTF": 11,
    "Comentarios": "En revisión de CV´s",
    "Fecha Inicio Búsqueda": "2026-03-10",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Margarita Araneda",
    "Equipo TA": "OVH",
    "Gerencia": "Proyectos y Construcción",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Daniel Bravo",
    "Cargo": "Director (confidencial)",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "Reemplazo",
    "Estado": "Activa",
    "TTF": 13,
    "Comentarios": "En revisión de CV´s",
    "Fecha Inicio Búsqueda": "2026-03-06",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Margarita Araneda",
    "Equipo TA": "OVH",
    "Gerencia": "Proyectos y Construcción",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Daniel Bravo",
    "Cargo": "Director (confidencial)",
    "Familia de cargo": "Middle Management",
    "¿A quién reemplaza?": "Reemplazo",
    "Estado": "Activa",
    "TTF": 13,
    "Comentarios": "En revisión de CV´s",
    "Fecha Inicio Búsqueda": "2026-03-06",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Marketing y Experiencia",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Cathia Escobar",
    "Cargo": "PM Studios",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "",
    "Estado": "Activa",
    "TTF": 32932,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-24",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "Camila Rivas",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Marketing y Experiencia",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Carlos Esteban",
    "Cargo": "Administrativo de Pagos y Contratos (confidencial)",
    "Familia de cargo": "Administrativo",
    "¿A quién reemplaza?": "Confidencial",
    "Estado": "Activa",
    "TTF": 8,
    "Comentarios": "Pendiente publicación",
    "Fecha Inicio Búsqueda": "2026-03-13",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Marketing y Experiencia",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Daniela Back",
    "Cargo": "Jefe de Experiencia Clientes",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "",
    "Estado": "Activa",
    "TTF": 7,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-16",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Maria Jose Carrizo",
    "País": "Chile",
    "Coordinador TA Responsable": "",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Marketing y Experiencia",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Francisca Guerra",
    "Cargo": "Jefe de Marketing Pre y postnatal",
    "Familia de cargo": "Junior Management",
    "¿A quién reemplaza?": "Andrea Jones",
    "Estado": "Activa",
    "TTF": 14,
    "Comentarios": "Publicación ok, en revisión de cv, pendiente contacar referido de fonchi.",
    "Fecha Inicio Búsqueda": "2026-03-05",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Daniella Matta",
    "Equipo TA": "Operaciones",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Ricardo Fuertes",
    "Cargo": "Coordinador de Prevención Temporal",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Lizeth Laura",
    "Estado": "Activa",
    "TTF": 17,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-02",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Jose Mendoza",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia Estrategia y Performance",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Felipe Sandoval ",
    "Cargo": "Practicante de Control de Gestión",
    "Familia de cargo": "Practicante",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Activa",
    "TTF": 11,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-10",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Denisse Guarniz",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia Comercial Perú",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Kristine Plenge",
    "Cargo": "Jefe Comercial",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Renzo Moreno",
    "Estado": "Activa",
    "TTF": 9,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-12",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "Si"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Tania Guerra",
    "Equipo TA": "Operaciones",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Victor Quispe",
    "Cargo": "Practicante de Administración",
    "Familia de cargo": "Practicante",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Activa",
    "TTF": 3,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-20",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "No"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Tania Guerra",
    "Equipo TA": "Operaciones",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Victor Quispe",
    "Cargo": "Coordinador de Operaciones",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Activa",
    "TTF": 3,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-20",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "No"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Fernanda Armas",
    "Equipo TA": "Operaciones",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Renzo Moreno",
    "Cargo": "Practicante de Administración",
    "Familia de cargo": "Practicante",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Activa",
    "TTF": 3,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-20",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "No"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Fernanda Armas",
    "Equipo TA": "Operaciones",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Renzo Moreno",
    "Cargo": "Coordinador de Operaciones",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Activa",
    "TTF": 3,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-20",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "No"
  },
  {
    "HRBP": "Patricia Bustamante",
    "País": "Perú",
    "Coordinador TA Responsable": "Fernanda Armas",
    "Equipo TA": "Operaciones",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "Ricardo Fuertes",
    "Cargo": "Coordinador de Operaciones",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Nueva Vacante",
    "Estado": "Activa",
    "TTF": 3,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-20",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": "No"
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "-",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Reemplazo",
    "Líder": "Germán Quezada",
    "Cargo": "Ingeniero de Procesos Operacionales",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Patricia Gonzalez",
    "Estado": "Activa",
    "TTF": 10,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-11",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  },
  {
    "HRBP": "Seba Soto",
    "País": "Chile",
    "Coordinador TA Responsable": "",
    "Equipo TA": "OVH",
    "Gerencia": "Gerencia de Operaciones",
    "Motivo de Busqueda": "Nuevo HC",
    "Líder": "",
    "Cargo": "Jefe de Control Operacional",
    "Familia de cargo": "Especialista/Profesional",
    "¿A quién reemplaza?": "Vanessa Vera",
    "Estado": "Activa",
    "TTF": 2,
    "Comentarios": "",
    "Fecha Inicio Búsqueda": "2026-03-23",
    "Fecha Cubierta Búsqueda": "2026-03-24",
    "Forecast": ""
  }
];

export default vacanciesData;